name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  cancel-in-progress: true
  group: ci-${{github.head_ref || github.ref}}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
